In [42]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\bunyo\OneDrive\Desktop\git_dataset\9. Sales-Data-Analysis.csv")

In [3]:
df.head()

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,10452,07-11-2022,Fries,3.49,573.07,Online,Gift Card,Tom Jackson,London
1,10453,07-11-2022,Beverages,2.95,745.76,Online,Gift Card,Pablo Perez,Madrid
2,10454,07-11-2022,Sides & Other,4.99,200.40,In-store,Gift Card,Joao Silva,Lisbon
3,10455,08-11-2022,Burgers,12.99,569.67,In-store,Credit Card,Walter Muller,Berlin
4,10456,08-11-2022,Chicken Sandwiches,9.95,201.01,In-store,Credit Card,Walter Muller,Berlin

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        254 non-null    int64
 1   Date            254 non-null    object
 2   Product         254 non-null    object
 3   Price           254 non-null    float64
 4   Quantity        254 non-null    float64
 5   Purchase Type   254 non-null    object
 6   Payment Method  254 non-null    object
 7   Manager         254 non-null    object
 8   City            254 non-null    object
dtypes: float64(2), int64(1), object(6)
memory usage: 18.0+ KB

In [7]:
def tozala(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='object':
                df[col].fillna(df[col].mode()[0],inplace=True)
            else:
                df[col].fillna(df[col].mean(),inplace=True)
    return df

In [8]:
tozala(df)

,Order ID,Date,Product,Price,Quantity,Purchase Type,Payment Method,Manager,City
0,10452,07-11-2022,Fries,3.49,573.07,Online,Gift Card,Tom Jackson,London
1,10453,07-11-2022,Beverages,2.95,745.76,Online,Gift Card,Pablo Perez,Madrid
2,10454,07-11-2022,Sides & Other,4.99,200.40,In-store,Gift Card,Joao Silva,Lisbon
3,10455,08-11-2022,Burgers,12.99,569.67,In-store,Credit Card,Walter Muller,Berlin
4,10456,08-11-2022,Chicken Sandwiches,9.95,201.01,In-store,Credit Card,Walter Muller,Berlin
...,...,...,...,...,...,...,...,...,...
249,10709,28-12-2022,Sides & Other,4.99,200.40,Drive-thru,Gift Card,Walter Muller,Berlin
250,10710,29-12-2022,Burgers,12.99,754.43,Drive-thru,Gift Card,Walter Muller,Berlin
251,10711,29-12-2022,Chicken Sandwiches,9.95,281.41,Drive-thru,Gift Card,Walter Muller,Berlin
252,10712,29-12-2022,Fries,3.49,630.37,Drive-thru,Gift Card,Walter Muller,Berlin
253,10713,29-12-2022,Beverages,2.95,677.97,Drive-thru,Gift Card,Walter Muller,Berlin

In [9]:
from sklearn.preprocessing import LabelEncoder
labeling = LabelEncoder()

In [10]:
def encodla(df):
    for col in df.columns:
        if df[col].dtype=='object':
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col],prefix=col, dtype=int)
                df=pd.concat([df.drop(columns=[col]),dummies],axis=1)
            else:
                df[col]=labeling.fit_transform(df[col])
    return df

In [18]:
df = encodla(df)

In [12]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()

In [14]:
def scale_qil(df):
    num_col=df.select_dtypes(include=['int64','int32','float64']).columns.drop('Quantity')
    df[num_col]=minmax.fit_transform(df[num_col])
    return df

In [20]:
df = scale_qil(df)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Order ID                     254 non-null    float64
 1   Date                         254 non-null    float64
 2   Price                        254 non-null    float64
 3   Quantity                     254 non-null    float64
 4   Manager                      254 non-null    float64
 5   Product_Beverages            254 non-null    float64
 6   Product_Burgers              254 non-null    float64
 7   Product_Chicken Sandwiches   254 non-null    float64
 8   Product_Fries                254 non-null    float64
 9   Product_Sides & Other        254 non-null    float64
 10  Purchase Type_Drive-thru     254 non-null    float64
 11  Purchase Type_In-store       254 non-null    float64
 12  Purchase Type_Online         254 non-null    float64
 13  Payment Method_ Cash         254 non-null    float64
 14  Payment Method_ Credit Card  254 non-null    float64
 15  Payment Method_ Gift Card    254 non-null    float64
 16  City_Berlin                  254 non-null    float64
 17  City_Lisbon                  254 non-null    float64
 18  City_London                  254 non-null    float64
 19  City_Madrid                  254 non-null    float64
 20  City_Paris                   254 non-null    float64
dtypes: float64(21)
memory usage: 41.8 KB

# Datani Bolish

In [23]:
x = df.drop('Quantity', axis=1)

In [24]:
y = df['Quantity']

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# Linear regressiya

In [27]:
from sklearn.linear_model import LinearRegression
lrModel = LinearRegression()

In [28]:
lrModel.fit(x_train,y_train)

LinearRegression()

In [29]:
pred1 = lrModel.predict(x_test)

In [30]:
from sklearn.metrics import r2_score, mean_absolute_error

In [31]:
r2=r2_score(y_test,pred1)
mae=mean_absolute_error(y_test,pred1)

In [32]:
print(r2)
print(mae)

0.9748643171310364
23.831678737411526

# K fold cross validation

In [37]:
from sklearn.model_selection import KFold, cross_val_score

In [38]:
kf = KFold(n_splits=5,shuffle=True,random_state=24)

In [39]:
score = cross_val_score(lrModel,X=x,y=y,cv=kf,scoring='r2')

In [40]:
print(score)

[0.96102108 0.9759323  0.96966163 0.9574045  0.95824035]

In [43]:
print(np.mean(score))

0.9644519740582258

In [44]:
print(np.std(score))

0.007196674872002448